PUT http://localhost:3001/users/update-password
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY5Y2FkMGQ4NjQ2MTdiN2I2YjlkMjM2MSIsImlhdCI6MTc3NDkwMTA0MywiZXhwIjoxNzc0OTg3NDQzfQ.zQyU9gXnCx7-Q8mE7RbdUALh8_Nnp7STR_k8rqAGI-I
Content-Type: application/json

{
  "oldPassword": "Qwer1234#",
  "newPassword": "New@1234"
}