POST http://localhost:3001/auth/login
Content-Type: application/json

{
    "email": "anni@pani.com",
    "password": "New@1234"
}


POST http://localhost:3001/auth/refresh-token
Content-Type: application/json
{
    "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY5Y2FkMGQ4NjQ2MTdiN2I2YjlkMjM2MSIsImlhdCI6MTc3NDk0MzkwMSwiZXhwIjoxNzc1NTQ4NzAxfQ.Qx5wqsgIr48gqr9EvC9KUGmQ3XBxxxluwag9-Hnek"
}